import type { Locale } from "@/components/locale-provider";

export const copy = {
  en: {
    brand: "UMedia",
    brandTagline: "Universal drive",
    createTitle: "Secure your drive",
    createBody:
      "Create the administrator password for this installation. You will use it to unlock UMedia from now on.",
    createAction: "Create password",
    confirm: "Confirm password",
    email: "Email address",
    password: "Password",
    loginTitle: "Welcome back",
    loginBody: "Enter your administrator password to unlock your files.",
    loginAction: "Unlock drive",
    navFiles: "Files",
    expandFolder: "Expand",
    collapseFolder: "Collapse",
    navHome: "Home",
    navStarred: "Starred",
    navTrash: "Trash",
    navSettings: "Account",
    navStorageSettings: "Storage settings",
    navPrivacyPolicy: "Privacy Policy",
    navTermsAndConditions: "Terms and Conditions",
    searchFiles: "Search files",
    searchStorage: "Search storage",
    searchFilesPlaceholder: "Search all files and folders…",
    searchStoragePlaceholder: "Search in this drive…",
    logOut: "Log out",
    usedSpace: "Used space",
    usedSpaceFiles: "files",
    recentFiles: "Recent files",
    recentFolders: "Recent folders",
    noRecentFiles: "No recent files yet.",
    noRecentFolders: "No recent folders yet.",
    homeTitle: "Home",
    themeToggle: "Toggle theme",
    themeLight: "Light",
    themeDark: "Dark",
    themeSystem: "System",
    appearanceTitle: "Appearance",
    appearanceBody: "Choose light, dark, or match the device.",
    usersTitle: "Users",
    usersBody: "Create accounts and control who can administer this installation.",
    addUser: "Add user",
    name: "Name",
    optionalName: "Optional name",
    role: "Role",
    active: "Active",
    inactive: "Inactive",
    activateUser: "Activate",
    deactivateUser: "Deactivate",
    deleteUser: "Delete",
    createUser: "Create user",
    creatingUser: "Creating…",
    roleAdmin: "Admin",
    roleUser: "User",
    changeRole: "Change role",
    cancel: "Cancel",
    passwordMinimum: "Use at least 12 characters.",
    usersLoading: "Loading users…",
    noUsers: "No users found.",
    deleteUserTitle: "Delete user?",
    deleteUserBody: "This account will lose access to UMedia.",
    userCreated: "User created.",
    userUpdated: "User updated.",
    userDeleted: "User deleted.",
    usersLoadFailed: "Could not load users.",
    userCreateFailed: "Could not create user.",
    userUpdateFailed: "Could not update user.",
    userDeleteFailed: "Could not delete user.",
  },
  fa: {
    brand: "یومدیا",
    brandTagline: "فضای یکپارچه",
    createTitle: "فضای خود را امن کنید",
    createBody:
      "رمز مدیر این نصب را بسازید. از این پس برای بازکردن UMedia از همین رمز استفاده می‌کنید.",
    createAction: "ساخت رمز",
    confirm: "تکرار رمز",
    email: "ایمیل",
    password: "رمز عبور",
    loginTitle: "خوش آمدید",
    loginBody: "برای دسترسی به فایل‌ها رمز مدیر را وارد کنید.",
    loginAction: "باز کردن فضا",
    navFiles: "فایل‌ها",
    expandFolder: "بازکردن",
    collapseFolder: "بستن",
    navHome: "خانه",
    navStarred: "ستاره‌دارها",
    navTrash: "سطل آشغال",
    navSettings: "حساب",
    navStorageSettings: "تنظیمات ذخیره‌سازی",
    navPrivacyPolicy: "سیاست حفظ حریم خصوصی",
    navTermsAndConditions: "شرایط و ضوابط",
    searchFiles: "جستجوی فایل‌ها",
    searchStorage: "جستجوی فضای پروایدر",
    searchFilesPlaceholder: "جستجو در همه فایل‌ها و پوشه‌ها…",
    searchStoragePlaceholder: "جستجو در این درایو…",
    logOut: "خروج",
    usedSpace: "فضای استفاده‌شده",
    usedSpaceFiles: "فایل",
    recentFiles: "فایل‌های اخیر",
    recentFolders: "پوشه‌های اخیر",
    noRecentFiles: "هنوز فایل اخیری نیست.",
    noRecentFolders: "هنوز پوشهٔ بازی‌شده‌ای نیست.",
    homeTitle: "خانه",
    themeToggle: "تغییر تم",
    themeLight: "روشن",
    themeDark: "تیره",
    themeSystem: "سیستم",
    appearanceTitle: "ظاهر",
    appearanceBody: "روشن، تیره، یا مطابق دستگاه.",
    usersTitle: "کاربران",
    usersBody: "حساب‌ها را بسازید و دسترسی مدیریت این نصب را کنترل کنید.",
    addUser: "افزودن کاربر",
    name: "نام",
    optionalName: "نام اختیاری",
    role: "نقش",
    active: "فعال",
    inactive: "غیرفعال",
    activateUser: "فعال‌کردن",
    deactivateUser: "غیرفعال‌کردن",
    deleteUser: "حذف",
    createUser: "ساخت کاربر",
    creatingUser: "در حال ساخت…",
    roleAdmin: "مدیر",
    roleUser: "کاربر",
    changeRole: "تغییر نقش",
    cancel: "انصراف",
    passwordMinimum: "حداقل ۱۲ نویسه وارد کنید.",
    usersLoading: "در حال بارگذاری کاربران…",
    noUsers: "کاربری پیدا نشد.",
    deleteUserTitle: "کاربر حذف شود؟",
    deleteUserBody: "این حساب دسترسی خود به یومدیا را از دست می‌دهد.",
    userCreated: "کاربر ساخته شد.",
    userUpdated: "کاربر به‌روزرسانی شد.",
    userDeleted: "کاربر حذف شد.",
    usersLoadFailed: "بارگذاری کاربران انجام نشد.",
    userCreateFailed: "ساخت کاربر انجام نشد.",
    userUpdateFailed: "به‌روزرسانی کاربر انجام نشد.",
    userDeleteFailed: "حذف کاربر انجام نشد.",
  },
} as const satisfies Record<Locale, Record<string, string>>;

export function useCopy(locale: Locale) {
  return copy[locale];
}
