import type { Locale } from "@/components/locale-provider";

export const copy = {
  en: {
    brand: "UMedia",
    brandTagline: "Universal drive",
    createTitle: "Secure your drive",
    createBody:
      "Create the administrator password for this installation. You will use it to unlock UMedia from now on.",
    createAction: "Create password",
    confirm: "Confirm password",
    email: "Email address",
    password: "Password",
    loginTitle: "Welcome back",
    loginBody: "Enter your administrator password to unlock your files.",
    loginAction: "Unlock drive",
    navFiles: "Files",
    navNotifications: "Notifications",
    notificationsTitle: "Notifications",
    notificationsAll: "All",
    notificationsUnread: "Unread",
    notificationsRead: "Read",
    notificationsEmpty: "No notifications.",
    notificationsUnreadEmpty: "No unread notification",
    notificationsReadEmpty: "No read notifications.",
    operationFailed: "failed",
    operationUpload: "Upload",
    operationCopy: "Copy",
    operationMove: "Move",
    operationSync: "Storage sync",
    markAsRead: "Mark as read",
    notificationsLoadFailed: "Could not load notifications.",
    viewNotifications: "View notifications",
    temporarySubtitle: "Pointer clipboard",
    temporaryInstructions:
      "Pointer clipboard for moves and copies. Use ⋮ → Add to Temporary, then Paste here, or drag and drop items into this panel.",
    expandFolder: "Expand",
    collapseFolder: "Collapse",
    navHome: "Home",
    navStarred: "Starred",
    navTrash: "Trash",
    navSettings: "Account",
    navStorageSettings: "Storage settings",
    navPrivacyPolicy: "Privacy Policy",
    navTermsAndConditions: "Terms and Conditions",
    searchFiles: "Search files",
    searchStorage: "Search storage",
    searchFilesPlaceholder: "Search all files and folders…",
    searchStoragePlaceholder: "Search in this drive…",
    logOut: "Log out",
    usedSpace: "Used space",
    usedSpaceFiles: "files",
    recentFiles: "Recent files",
    recentFolders: "Recent folders",
    noRecentFiles: "No recent files yet.",
    noRecentFolders: "No recent folders yet.",
    homeTitle: "Home",
    themeToggle: "Toggle theme",
    themeLight: "Light",
    themeDark: "Dark",
    themeSystem: "System",
    appearanceTitle: "Appearance",
    appearanceBody: "Choose light, dark, or match the device.",
    usersTitle: "Users",
    usersBody: "Create accounts and control who can administer this installation.",
    addUser: "Add user",
    name: "Name",
    optionalName: "Optional name",
    role: "Role",
    active: "Active",
    inactive: "Inactive",
    activateUser: "Activate",
    deactivateUser: "Deactivate",
    deleteUser: "Delete",
    createUser: "Create user",
    creatingUser: "Creating…",
    roleAdmin: "Admin",
    roleUser: "User",
    changeRole: "Change role",
    cancel: "Cancel",
    passwordMinimum: "Use at least 12 characters.",
    usersLoading: "Loading users…",
    noUsers: "No users found.",
    deleteUserTitle: "Delete user?",
    deleteUserBody: "This account will lose access to UMedia.",
    userCreated: "User created.",
    userUpdated: "User updated.",
    userDeleted: "User deleted.",
    usersLoadFailed: "Could not load users.",
    userCreateFailed: "Could not create user.",
    userUpdateFailed: "Could not update user.",
    userDeleteFailed: "Could not delete user.",
    storageSettingsTitle: "Storage settings",
    storageSettingsBody: "Manage storage connections and where new files are stored.",
    storageConnections: "Connections",
    storageConnectionsBody: "Storage providers connected to your library.",
    storageConnectionCount: "{count} connections",
    storageOneConnection: "1 connection",
    connectionConfigured: "Connected",
    connectionNeedsAttention: "Needs attention",
    storageLoading: "Loading storage connections…",
    storageLoadFailed: "Could not load storage connections.",
    storageEmpty: "No storage connections yet.",
    addStorage: "Add storage",
    syncNow: "Sync",
    syncing: "Syncing…",
    syncStarted: "Sync started. It will continue in the background.",
    syncAlreadyRunning: "A sync is already running in the background.",
    syncFailed: "Could not sync this connection.",
    connectionPreferences: "Connection settings",
    importExisting: "Import existing objects",
    importExistingHelp: "Show objects already on this provider in your library, including on sync.",
    mirrorStructure: "Mirror folder structure",
    mirrorTelegramHelp: "Telegram channels are flat and do not support folders.",
    mirrorStructureHelp: "Apply supported library folder moves and renames to this provider.",
    removeStorage: "Remove storage",
    removeStorageTitle: "Remove storage?",
    removeStorageBody: "Library files on {name} go to Trash. Provider bytes are not deleted.",
    storageRemoved: "Storage connection removed.",
    storageRemoveFailed: "Could not remove this connection.",
    storageUpdateFailed: "Could not update connection.",
    renameConnection: "Rename",
    renameConnectionLabel: "Connection name",
    saveName: "Save",
    connectionRenamed: "Connection renamed.",
    connectionNameHelp:
      "Also its S3 bucket name: 3–63 lowercase letters, numbers, and hyphens.",
  },
  fa: {
    brand: "یومدیا",
    brandTagline: "فضای یکپارچه",
    createTitle: "فضای خود را امن کنید",
    createBody:
      "رمز مدیر این نصب را بسازید. از این پس برای بازکردن UMedia از همین رمز استفاده می‌کنید.",
    createAction: "ساخت رمز",
    confirm: "تکرار رمز",
    email: "ایمیل",
    password: "رمز عبور",
    loginTitle: "خوش آمدید",
    loginBody: "برای دسترسی به فایل‌ها رمز مدیر را وارد کنید.",
    loginAction: "باز کردن فضا",
    navFiles: "فایل‌ها",
    navNotifications: "اعلان‌ها",
    notificationsTitle: "اعلان‌ها",
    notificationsAll: "همه",
    notificationsUnread: "خوانده‌نشده",
    notificationsRead: "خوانده‌شده",
    notificationsEmpty: "اعلانی ندارید.",
    notificationsUnreadEmpty: "اعلان خوانده‌نشده‌ای ندارید.",
    notificationsReadEmpty: "اعلان خوانده‌شده‌ای ندارید.",
    operationFailed: "ناموفق بود",
    operationUpload: "آپلود",
    operationCopy: "کپی",
    operationMove: "جابه‌جایی",
    operationSync: "همگام‌سازی فضای ذخیره‌سازی",
    markAsRead: "خوانده شد",
    notificationsLoadFailed: "بارگذاری اعلان‌ها انجام نشد.",
    viewNotifications: "دیدن اعلان‌ها",
    temporarySubtitle: "کلیپ‌بورد موقت",
    temporaryInstructions:
      "کلیپ‌بورد موقت برای جابه‌جایی و کپی است. از ⋮ گزینهٔ افزودن به موقت را بزنید و اینجا جای‌گذاری کنید، یا فایل‌ها را بکشید و در این پنل رها کنید.",
    expandFolder: "بازکردن",
    collapseFolder: "بستن",
    navHome: "خانه",
    navStarred: "ستاره‌دارها",
    navTrash: "سطل آشغال",
    navSettings: "حساب",
    navStorageSettings: "تنظیمات ذخیره‌سازی",
    navPrivacyPolicy: "سیاست حفظ حریم خصوصی",
    navTermsAndConditions: "شرایط و ضوابط",
    searchFiles: "جستجوی فایل‌ها",
    searchStorage: "جستجوی فضای پروایدر",
    searchFilesPlaceholder: "جستجو در همه فایل‌ها و پوشه‌ها…",
    searchStoragePlaceholder: "جستجو در این درایو…",
    logOut: "خروج",
    usedSpace: "فضای استفاده‌شده",
    usedSpaceFiles: "فایل",
    recentFiles: "فایل‌های اخیر",
    recentFolders: "پوشه‌های اخیر",
    noRecentFiles: "هنوز فایل اخیری نیست.",
    noRecentFolders: "هنوز پوشهٔ بازی‌شده‌ای نیست.",
    homeTitle: "خانه",
    themeToggle: "تغییر تم",
    themeLight: "روشن",
    themeDark: "تیره",
    themeSystem: "سیستم",
    appearanceTitle: "ظاهر",
    appearanceBody: "روشن، تیره، یا مطابق دستگاه.",
    usersTitle: "کاربران",
    usersBody: "حساب‌ها را بسازید و دسترسی مدیریت این نصب را کنترل کنید.",
    addUser: "افزودن کاربر",
    name: "نام",
    optionalName: "نام اختیاری",
    role: "نقش",
    active: "فعال",
    inactive: "غیرفعال",
    activateUser: "فعال‌کردن",
    deactivateUser: "غیرفعال‌کردن",
    deleteUser: "حذف",
    createUser: "ساخت کاربر",
    creatingUser: "در حال ساخت…",
    roleAdmin: "مدیر",
    roleUser: "کاربر",
    changeRole: "تغییر نقش",
    cancel: "انصراف",
    passwordMinimum: "حداقل ۱۲ نویسه وارد کنید.",
    usersLoading: "در حال بارگذاری کاربران…",
    noUsers: "کاربری پیدا نشد.",
    deleteUserTitle: "کاربر حذف شود؟",
    deleteUserBody: "این حساب دسترسی خود به یومدیا را از دست می‌دهد.",
    userCreated: "کاربر ساخته شد.",
    userUpdated: "کاربر به‌روزرسانی شد.",
    userDeleted: "کاربر حذف شد.",
    usersLoadFailed: "بارگذاری کاربران انجام نشد.",
    userCreateFailed: "ساخت کاربر انجام نشد.",
    userUpdateFailed: "به‌روزرسانی کاربر انجام نشد.",
    userDeleteFailed: "حذف کاربر انجام نشد.",
    storageSettingsTitle: "تنظیمات فضای ذخیره‌سازی",
    storageSettingsBody: "اتصال‌های ذخیره‌سازی و محل ذخیرهٔ فایل‌های جدید را مدیریت کنید.",
    storageConnections: "اتصال‌ها",
    storageConnectionsBody: "فضاهای ذخیره‌سازی متصل به کتابخانهٔ شما.",
    storageConnectionCount: "{count} اتصال",
    storageOneConnection: "یک اتصال",
    connectionConfigured: "متصل",
    connectionNeedsAttention: "نیازمند بررسی",
    storageLoading: "در حال بارگذاری اتصال‌ها…",
    storageLoadFailed: "بارگذاری اتصال‌های ذخیره‌سازی انجام نشد.",
    storageEmpty: "هنوز فضای ذخیره‌سازی‌ای متصل نشده است.",
    addStorage: "افزودن فضای ذخیره‌سازی",
    syncNow: "همگام‌سازی",
    syncing: "در حال همگام‌سازی…",
    syncStarted: "همگام‌سازی شروع شد و در پس‌زمینه ادامه می‌یابد.",
    syncAlreadyRunning: "همگام‌سازی این اتصال در حال اجراست.",
    syncFailed: "همگام‌سازی این اتصال انجام نشد.",
    connectionPreferences: "تنظیمات اتصال",
    importExisting: "واردکردن موارد موجود",
    importExistingHelp: "موارد موجود در این ارائه‌دهنده را در کتابخانه نمایش بده؛ هنگام همگام‌سازی هم بررسی می‌شود.",
    mirrorStructure: "همگام‌کردن ساختار پوشه‌ها",
    mirrorTelegramHelp: "کانال‌های تلگرام تخت هستند و از پوشه پشتیبانی نمی‌کنند.",
    mirrorStructureHelp: "تغییر نام و جابه‌جایی پوشه‌های کتابخانه را در صورت پشتیبانی، روی این ارائه‌دهنده هم اعمال کن.",
    removeStorage: "حذف اتصال",
    removeStorageTitle: "اتصال حذف شود؟",
    removeStorageBody: "فایل‌های کتابخانهٔ {name} به سطل زباله می‌روند. فایل‌های خود ارائه‌دهنده حذف نمی‌شوند.",
    storageRemoved: "اتصال ذخیره‌سازی حذف شد.",
    storageRemoveFailed: "حذف اتصال انجام نشد.",
    storageUpdateFailed: "به‌روزرسانی اتصال انجام نشد.",
    renameConnection: "تغییر نام",
    renameConnectionLabel: "نام اتصال",
    saveName: "ذخیره",
    connectionRenamed: "نام اتصال تغییر کرد.",
    connectionNameHelp:
      "این نام، نام باکت S3 هم هست: ۳ تا ۶۳ حرف کوچک انگلیسی، عدد یا خط تیره.",
  },
} as const satisfies Record<Locale, Record<string, string>>;

export function useCopy(locale: Locale) {
  return copy[locale];
}
